# Generated by Django 5.1 on 2024-08-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_gym_owner_alter_client_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gym_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.gymowner'),
        ),
        migrations.AlterField(
            model_name='client',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50),
        ),
    ]
